#!/usr/bin/env bash
#globah haproxy configuration to accept encrypted traffic for subdomain www..
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:443 ssl crt /etc/letsencrypt/csr/www.getrukky.tech/0000_csr-certbot.pem
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 100.27.14.91 check

#frontend configuration
frontend http-in
    bind *:80
    default_backend servers

# Backend configuration distributing traffic
backend servers
    balance roundrobin
    server 92102-web-01 100.27.14.91
    server 92102-web-02 34.232.52.68

