#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu linux distro.
# The installed server listens to port 80 (HTTP) for connection


sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER:$USER" /var/www
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
