#!/usr/bin/env bash
# This script installs and Configures a Nginx server
# such that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER:$USER" /var/www
echo 'Hello World!' > /var/www/html/index.html

# these are the new server block for redirection
sudo bash -c 'cat > /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name getrukky.tech;
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOF'

# this part enables the server block and disable the default one
sudo ln -s /etc/nginx/sitesi-available/redirect_me /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default

# Test the configuration and restart Nginx
sudo nginx -t
sudo systemctl restart nginx

