#!/usr/bin/env bash
# This configures Nginx to add a custom header to its HTTP response

# This updates package list and installs nginx
sudo apt-get update
sudo apt-get -y install nginx
# This block edits the Nginx configuration file and 
# adds the custom header with the server hostname to the HTTP response.
sudo sed -i "/http {/a \        add_header X-Served-By \"$(hostname)\";" /etc/nginx/nginx.conf
sudo service nginx restart





