#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# this will Update system packages and install haproxy# this will Update system packages and install haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown -R "$USER:$USER" /etc/haproxy/

# for configuring HAProxy to forward traffic to web-01 and web-02
printf %s "
#frontend configuration
frontend http-in
    bind *:80
    default_backend servers

# Backend configuration distributing traffic 
backend servers
    balance roundrobin
    server 92102-web-01 100.27.14.91
    server 92102-web-02 34.232.52.68
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

