#!/usr/bin/env bash
# bash script fixing nginx not listening on port 80 to listen on port 80

sudo sed - i 's/listen 80 default_server;/listen 80;/'
/etc/nginx/sites-available/default

# Restart Nginx service
sudo systemctl restart nginx
